brokers:
  - id: 0
    host: '0.0.0.0'
  - id: 1
    host: 'broker1'
port: 9092
topics:
  - name: 'topic1'
    partitions: 3
    replication_factor: 2
  - name: 'topic2'
    partitions: 5
    replication_factor: 2
