brokers:
  - id: 1
    hostname: 'broker1'
    port: 9092
  - id: 2
    hostname: 'broker2'
    port: 9092
  - id: 3
    hostname: 'broker3'
    port: 9092
  - id: 4
    hostname: 'broker4'
    port: 9092
  - id: 5
    hostname: 'broker5'
    port: 9092
topics:
  - name: 'topic1'
    partitions: 3
    replicationFactor: 2
  - name: 'topic2'
    partitions: 5
    replicationFactor: 2
